
  
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'public/**/*'

Rails:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - capybara
    - staging
    - production
    - e2e

Style/Documentation:
  Enabled: false

Style/Send:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '{}'
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
    '%Q': '{}'

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false