version: "3.7"

services:
  postgres:
    container_name: postgres-container
    image: postgres:11-alpine
    ports: 
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always
    networks: 
      - app-network

networks:
  app-network:
    driver: "bridge"

volumes:
  postgres: {}
